version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '04:00'
      timezone: US/Arizona
    open-pull-requests-limit: 6
    ignore:
      - dependency-name: convict
        versions:
          - '> 4.4.1'
      - dependency-name: '@types/convict'
        versions:
          - '> 4.2.1'
      - dependency-name: '@types/node'
        versions:
          - '>= 17.0.0'
