version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '04:00'
      timezone: US/Arizona
    # Disable version updates, only get security updates
    open-pull-requests-limit: 0
    assignees:
      - busma13
      - sotojn
    # ignore:
    #   - dependency-name: convict
    #     versions:
    #       - '> 4.4.1'
    #   - dependency-name: '@types/convict'
    #     versions:
    #       - '> 4.2.1'
    #   - dependency-name: '@types/node'
    #     versions:
    #       - '>= 17.0.0'
  - package-ecosystem: npm
    directory: '/website'
    schedule:
      interval: monthly
      time: '04:00'
      timezone: US/Arizona
    ignore:
      - dependency-name: "*"
    # Disable version updates, only get security updates
    open-pull-requests-limit: 0
    assignees:
      - godber
      - sotojn
      - busma13
