packages:
  - 'asset'
  - 'packages/*'

allowBuilds:
  '@confluentinc/kafka-javascript': true
  '@parcel/watcher': true
  dtrace-provider: true
  unrs-resolver: true

blockExoticSubdeps: true

minimumReleaseAge: 1440 # 1 day

minimumReleaseAgeExclude:
  - '@terascope/*'
  - teraslice-client-js
  - teraslice-test-harness

trustPolicy: no-downgrade

trustPolicyExclude:
  - 'semver@6.3.1' # false positive - maintainer change

publicHoistPattern:
  - "@confluentinc/kafka-javascript"
