// NOTE: This code is auto-generated by `teraslice-cli assets registry`
// any manual changes will be lost next time this gets auto-generated.

import KafkaDeadLetterAPI from '../src/kafka_dead_letter/api';
import KafkaDeadLetterSchema from '../src/kafka_dead_letter/schema';

import KafkaReaderAPI from '../src/kafka_reader_api/api';
import KafkaReaderAPISchema from '../src/kafka_reader_api/schema';

import KafkaReaderFetcher from '../src/kafka_reader/fetcher';
import KafkaReaderSchema from '../src/kafka_reader/schema';
import KafkaReaderSlicer from '../src/kafka_reader/slicer';

import KafkaSenderAPI from '../src/kafka_sender_api/api';
import KafkaSenderAPISchema from '../src/kafka_sender_api/schema';

import KafkaSender from '../src/kafka_sender/processor';
import KafkaSenderSchema from '../src/kafka_sender/schema';

export const ASSETS = {
    kafka_dead_letter: {
        API: KafkaDeadLetterAPI,
        Schema: KafkaDeadLetterSchema,
    },
    kafka_reader_api: {
        API: KafkaReaderAPI,
        Schema: KafkaReaderAPISchema,
    },
    kafka_reader: {
        Fetcher: KafkaReaderFetcher,
        Schema: KafkaReaderSchema,
        Slicer: KafkaReaderSlicer,
    },
    kafka_sender_api: {
        API: KafkaSenderAPI,
        Schema: KafkaSenderAPISchema,
    },
    kafka_sender: {
        Processor: KafkaSender,
        Schema: KafkaSenderSchema,
    },
};
