name: Build, Publish and Release Teraslice Asset
run-name: ${{ github.actor }} is building, publishing and releasing the Teraslice Asset
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  call-asset-build:
    if: github.event.pull_request.merged == true
    uses: terascope/workflows/.github/workflows/asset-build-and-publish.yml@f264abdd51e72bf572199763ed5c1de93334e99a
    secrets: inherit
