name: Build and Publish Teraslice Asset
run-name: ${{ github.actor }} is building and publishing the Teraslice Asset
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  call-asset-build:
    uses: terascope/workflows/.github/workflows/asset-build-and-publish.yml@bb318f6a11fa77b714c16ee3f4c7c02689d5bef9
    secrets: inherit
