name: Build and Publish Teraslice Asset
run-name: ${{ github.actor }} is building and publishing the Teraslice Asset
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  call-asset-build:
    uses: terascope/workflows/.github/workflows/asset-build-and-publish.yml@f86f716e47d989b939d978befa7721c1f5b10134
    secrets: inherit
