name: Build, Publish and Release Teraslice Asset
run-name: ${{ github.actor }} is building, publishing and releasing the Teraslice Asset
on:
  pull_request:
    branches:
      - master
      - release/kafka-assets-v*
    types:
      - closed

permissions: {}
  
jobs:
  call-asset-build:
    if: github.event.pull_request.merged == true
    uses: terascope/workflows/.github/workflows/asset-build-and-publish.yml@ee93e5655fd79976999f2c665ac1b6d7e334ec3b
    with:
      teraslice-cli-version: ${{ startsWith(github.base_ref, 'release/kafka-assets-v') && 'prerelease' || 'latest' }}
    permissions:
      id-token: write  # Required for OIDC
      contents: read
      pages: write     # to deploy to Pages
    secrets:
      RELEASES_PRIVATE_KEY: ${{ secrets.RELEASES_PRIVATE_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
