name: Build, Publish and Release Teraslice Asset
run-name: ${{ github.actor }} is building, publishing and releasing the Teraslice Asset
on:
  pull_request:
    branches:
      - master
      - release/kafka-assets-v*
    types:
      - closed

permissions:
  id-token: write  # Required for OIDC
  contents: write
  pages: write     # to deploy to Pages
  
jobs:
  call-master-asset-build:
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    uses: terascope/workflows/.github/workflows/asset-build-and-publish.yml@main
    secrets: inherit

  call-prerelease-asset-build:
    if: github.event.pull_request.merged == true && startsWith(github.base_ref, 'release/kafka-assets-v')
    uses: terascope/workflows/.github/workflows/prerelease-asset-build-and-publish.yml@main
    secrets: inherit
