name: Daily Docker Cache

on:
  schedule:
    - cron: '0 10 30 * 1-5' # Monday - Friday at 3:30am Arizona Time
  workflow_dispatch:

jobs:
  call-refresh-docker-cache-workflow:
    uses: terascope/workflows/.github/workflows/refresh-docker-cache.yml@f264abdd51e72bf572199763ed5c1de93334e99a
    secrets: inherit
