name: Daily Docker Cache

on:
  schedule:
    - cron: '30 10 * * 1-5' # Monday - Friday at 3:30am Arizona Time
  workflow_dispatch:

permissions: {}

jobs:
  call-refresh-docker-cache-workflow:
    uses: terascope/workflows/.github/workflows/refresh-docker-cache.yml@ee93e5655fd79976999f2c665ac1b6d7e334ec3b
    permissions:
      actions: write
      contents: read
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
