name: Daily Docker Cache

on:
  schedule:
    - cron: '0 10 30 * 1-5' # Monday - Friday at 3:30am Arizona Time
  workflow_dispatch:

jobs:
  call-refresh-docker-cache-workflow:
    uses: terascope/workflows/.github/workflows/refresh-docker-cache.yml@2a097b4af7eb81cebc7d602ad9ab2f1ef7b979cc
    secrets: inherit
