name: Daily Docker Cache

on:
  schedule:
    - cron: '30 10 * * 1-5' # Monday - Friday at 3:30am Arizona Time
  workflow_dispatch:

permissions: {}

jobs:
  call-refresh-docker-cache-workflow:
    uses: terascope/workflows/.github/workflows/refresh-docker-cache.yml@b7b03054122f0f4c73a15f523bb224588552f55c
    permissions:
      actions: write
      contents: read
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
