name: Daily Docker Cache

on:
  schedule:
    - cron: '0 10 30 * 1-5' # Monday - Friday at 3:30am Arizona Time
  workflow_dispatch:

jobs:
  call-refresh-docker-cache-workflow:
    uses: terascope/workflows/.github/workflows/refresh-docker-cache.yml@5307c8fb58de8d120cc025907cd417407f6c17cb
    secrets: inherit
