name: Publish Test
run-name: publish test

on:
  pull_request:
    branches: [ master ]

jobs:

  publish-test:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Register npm token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: whoami
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and build packages
        run: yarn setup

      - name: Publish to npm
        run: 'yarn publish:changed'
