name: Test Teraslice Asset
run-name: ${{ github.actor }} is testing the Teraslice Asset
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'release/kafka-assets-v*'
  pull_request:
    branches:
      - master
      - 'release/kafka-assets-v*'

permissions: {}

jobs:
  call-asset-test-workflow:
    uses: terascope/workflows/.github/workflows/asset-test.yml@ee93e5655fd79976999f2c665ac1b6d7e334ec3b
    with:
      teraslice-cli-version: ${{ (startsWith(github.ref, 'refs/heads/release/kafka-assets-v') || startsWith(github.base_ref, 'release/kafka-assets-v')) && 'prerelease' || 'latest' }}
    permissions:
      actions: read
      contents: read
      pull-requests: write
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
