name: Test Teraslice Asset
run-name: ${{ github.actor }} is testing the Teraslice Prerelease Asset
on:
  workflow_dispatch:
  push:
    branches:
      - 'release/kafka-assets-v*'
  pull_request:
    branches:
      - 'release/kafka-assets-v*'

permissions: {}

jobs:
  call-asset-test-workflow:
    uses: terascope/workflows/.github/workflows/prerelease-asset-test.yml@d2864085b6d36798749fce3dd549dae10283f76a
    permissions:
      actions: read
      contents: read
      pull-requests: write
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
